version: "3"

networks:
  traefiknet:
    name: proxy_traefiknet
    external: true

services:
  client:
    container_name: big-data-ecommerce-client
    build:
      dockerfile: nextjs.Dockerfile.prod
    restart: always
    image: big-data-ecommerce-client:latest
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_PROTOCOL: ${NEXT_PUBLIC_API_PROTOCOL}
      NEXT_PUBLIC_API_HOSTNAME: ${NEXT_PUBLIC_API_HOSTNAME}
      NEXT_PUBLIC_API_PORT: ${NEXT_PUBLIC_API_PORT}
      NEXT_PUBLIC_UPLOAD_PATH: ${NEXT_PUBLIC_UPLOAD_PATH}
      PREVIEW_SECRET: ${PREVIEW_SECRET}
    ports:
      - 3100:3000
    networks:
      - traefiknet
    labels:
      - traefik.enable=true
      - traefik.http.routers.big-data-ecommerce-client.entrypoints=websecure
      - traefik.http.routers.big-data-ecommerce-client.rule=Host(`big-data-ecommerce.davidaloba.xyz`)
      - traefik.http.routers.big-data-ecommerce-client.tls=true
      - traefik.http.routers.big-data-ecommerce-client.tls.certresolver=myresolver

  server:
    container_name: big-data-ecommerce-server
    build:
      dockerfile: strapi.Dockerfile.prod
    image: big-data-ecommerce-server:latest
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${NEXT_PUBLIC_API_PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      PREVIEW_SECRET: ${PREVIEW_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./.env:/opt/app/.env
      - ./server/package.json:/opt/app/package.json
      - ./server/yarn.lock:/opt/app/yarn.lock
      - ./server/config:/opt/app/config
      - ./server/src:/opt/app/src
      - ./server/public/uploads:/opt/app/public/uploads
    ports:
      - 1377:1337
    networks:
      - traefiknet
    labels:
      - traefik.enable=true
      - traefik.http.routers.big-data-ecommerce-server.entrypoints=websecure
      - traefik.http.routers.big-data-ecommerce-server.rule=Host(`cms.big-data-ecommerce.davidaloba.xyz`)
      - traefik.http.routers.big-data-ecommerce-server.tls=true
      - traefik.http.routers.big-data-ecommerce-server.tls.certresolver=myresolver
