version: '3'

networks:
  proxy:
    name: proxy
    external: true
    

services:
  nextjs:
    container_name: client
    build: ./client
    image: next_simple:latest
    # restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PREVIEW_SECRET: ${PREVIEW_SECRET}
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - proxy
    depends_on:
      - strapi

  strapi:
    container_name: server
    build: ./server
    image: strapi:latest
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
      CLIENT_URL: ${CLIENT_URL}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      PREVIEW_SECRET: ${PREVIEW_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./server/package.json:/opt/app/package.json
      - ./server/yarn.lock:/opt/app/yarn.lock
      - ./server/config:/opt/app/config
      - ./server/src:/opt/app/src
      - ./server/.env:/opt/app/.env
      - ./server/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - proxy
  