version: '3'

networks:
  traefiknet:
    name: proxy_traefiknet
    external: true
    

services:
  client:
    container_name: yinkasamuels-client
    build:
      dockerfile: nextjs.Dockerfile.prod
    restart: always
    image: yinkasamuels-client:latest
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${STRAPI_URL}
      PREVIEW_SECRET: ${PREVIEW_SECRET}
    ports:
      - 3100:3000
    networks:
      - traefiknet
    labels:
      - traefik.enable=true
      - traefik.http.routers.yinkasamuels-client.entrypoints=websecure
      - traefik.http.routers.yinkasamuels-client.rule=Host(`yinkasamuels.com`)
      - traefik.http.routers.yinkasamuels-client.tls=true
      - traefik.http.routers.yinkasamuels-client.tls.certresolver=myresolver

  server:
    container_name: yinkasamuels-server
    build:
      dockerfile: strapi.Dockerfile.prod
    image: yinkasamuels-server:latest
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PUBLIC_URL: ${STRAPI_URL}
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      PREVIEW_SECRET: ${PREVIEW_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./.env:/opt/app/.env
      - ./server/package.json:/opt/app/package.json
      - ./server/yarn.lock:/opt/app/yarn.lock
      - ./server/config:/opt/app/config
      - ./server/src:/opt/app/src
      - ./server/public/uploads:/opt/app/public/uploads
    ports:
      - 1377:1337
    networks:
      - traefiknet
    labels:
      - traefik.enable=true
      - traefik.http.routers.yinkasamuels-server.entrypoints=websecure
      - traefik.http.routers.yinkasamuels-server.rule=Host(`cms.yinkasamuels.com`)
      - traefik.http.routers.yinkasamuels-server.tls=true
      - traefik.http.routers.yinkasamuels-server.tls.certresolver=myresolver
  